[package]
name = "sync_step_machine"
version = "0.1.2"
edition = "2021"
description = "A Simple Step Machine to improve code maintenance."
license = "MIT"

[lib]
crate-type = ["rlib"]

[dependencies]

[repository]
url = "https://github.com/citrixorange/StepMachine"
